# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
      working-directory: ./scraping
    - run: yarn test
      working-directory: ./scraping
    - name: Deploy
      env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          SECURITY_GROUP: ${{ secrets.SECURITY_GROUP }}
      run: |
          # https://github.com/haythem/public-ip
          IP_ADDRESS=`echo ${{ steps.ip.outputs.ipv4 }}`

          # AWS CLIをインストール
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

          # AWS CLIに設定をする
          printf "${ACCESS_KEY}\n${SECRET_ACCESS_KEY}\nap-northeast-1\njson\n" | aws configure --profile eyemovic-dev
          aws configure get aws_access_key_id --profile eyemovic-dev

          
          # SSH接続して、git pullする
          echo "$PRIVATE_KEY" > github_key && chmod 600 github_key 
          ssh -o StrictHostKeyChecking=no -i github_key ${USER_NAME}@${HOST_NAME} '
          cd /home/centos/transition_test &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main &&
          node -v &&
          npm install -g yarn && 
          cd test_sample &&
          yarn install &&
          cd ../scraping &&
          yarn install &&
          forever start /home/centos/transition_test/test_sample/bin/www
          '


          